### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kpilszak**
List and links of favourite sites

### CODE REVIEW

**Review by ppremk — APPROVED** [review]
👍

**Comment by ppremk** [comment]
hey there.. if it is ok by you.. could you please add me as an collaborator to this repo? I could help approve. Upon approval, you can remove me as an collaborator 🙂

**Comment by ppremk** [comment]
Looks like it is approved now. Good luck and thanks! 🙂

**Comment by kpilszak** [comment]
Thanks a lot @ppremk ! Now how can I resume my training? No new Issues or pull requests appeared

**Comment by ppremk** [comment]
Hi @kpilszak we had tried to reset the course flow from the backend service and I am afraid that it did not yield the results we needed to help you continue with the course. At this point I would propose to leave this course and restart it again to ensure completion in the right flow. It is not optimal but it would ensure that you are able to complete it. Hope this helps. Please let know if there is anything else we could be of help. Good Luck 🙂

**Pull request merged**
